# Generated by Django 2.2.15 on 2020-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
