# Generated by Django 2.2.15 on 2020-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_profile_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
