# Generated by Django 2.2.15 on 2020-12-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201227_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social',
            new_name='social_github',
        ),
    ]
