# Generated by Django 2.2.15 on 2020-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201227_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
